/* eslint-disable */
// @ts-nocheck
// 由 unplugin-vue-components 自动生成
// 了解更多: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppMain: typeof import('./../src/layout/components/AppMain.vue')['default']
    Block: typeof import('./../src/components/discussion/block.vue')['default']
    Breadcrumb: typeof import('./../src/components/Breadcrumb/index.vue')['default']
    ChooseQuestion: typeof import('./../src/components/ExamComponents/ChooseQuestion/index.vue')['default']
    ClassSelect: typeof import('./../src/components/ClassSelect/index.vue')['default']
    Discussion: typeof import('./../src/components/discussion/index.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ErrorAlert: typeof import('./../src/components/ErrorAlert/index.vue')['default']
    ExamTimer: typeof import('./../src/components/ExamTimer/index.vue')['default']
    FileUpload: typeof import('./../src/components/FileUpload/index.vue')['default']
    Hamburger: typeof import('./../src/components/Hamburger/index.vue')['default']
    Item: typeof import('./../src/layout/components/Sidebar/Item.vue')['default']
    Link: typeof import('./../src/layout/components/Sidebar/Link.vue')['default']
    Local: typeof import('./../src/components/FileUpload/local.vue')['default']
    Logo: typeof import('./../src/layout/components/Sidebar/Logo.vue')['default']
    Navbar: typeof import('./../src/layout/components/Navbar.vue')['default']
    NoticeDialog: typeof import('./../src/components/notice/noticeDialog/index.vue')['default']
    RepoDialog: typeof import('./../src/components/repo/repoDialog/index.vue')['default']
    RepoSelect: typeof import('./../src/components/RepoSelect/index.vue')['default']
    RichTextEditor: typeof import('./../src/components/RichTextEditor/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../src/layout/components/Sidebar/index.vue')['default']
    SidebarItem: typeof import('./../src/layout/components/Sidebar/SidebarItem.vue')['default']
    SlideCaptcha: typeof import('./../src/components/SlideCaptcha/index.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
